# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xc',
                'doc_host': 'https://syeung2.github.io',
                'git_url': 'https://github.com/syeung2/xc',
                'lib_path': 'xc'},
  'syms': {'xc.core': {'xc.core.foo': ('core.html#foo', 'xc/core.py')}}}
